# Generated by Django 5.2.6 on 2025-09-16 19:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0004_telegramgroup_remove_emailsettings_default_bcc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('template', models.FileField(blank=True, null=True, upload_to='report_templates/')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('day_of_week', models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='Mon', max_length=3)),
                ('day_of_month', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('time', models.TimeField()),
                ('send_email', models.BooleanField(default=False)),
                ('send_telegram', models.BooleanField(default=False)),
                ('telegram_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.telegramgroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
