# Generated by Django 5.2.6 on 2025-09-18 03:28

import django.utils.timezone
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_telegramgroup_remove_emailsettings_default_bcc_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('template', models.FileField(blank=True, null=True, upload_to=reports.models.report_template_path)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='Mon', max_length=3)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1)),
                ('time', models.TimeField()),
                ('send_email', models.BooleanField(default=False)),
                ('send_telegram', models.BooleanField(default=False)),
                ('telegram_groups', models.ManyToManyField(blank=True, to='notifications.telegramgroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='ReportSchedule',
        ),
    ]
