# Generated by Django 5.2.6 on 2025-09-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, help_text='SMTP server host', max_length=255)),
                ('port', models.PositiveIntegerField(default=587, help_text='SMTP server port')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, help_text='Use an App Password if using Gmail/OAuth', max_length=255)),
                ('from_name', models.CharField(blank=True, default='RFMS Notifications', max_length=255)),
                ('from_address', models.EmailField(blank=True, default='no-reply@rfms.local', max_length=254)),
                ('encryption', models.CharField(choices=[('STARTTLS', 'STARTTLS'), ('SSL/TLS', 'SSL/TLS'), ('None', 'None')], default='STARTTLS', max_length=10)),
                ('recipients', models.JSONField(default=dict, help_text="Default 'to', 'cc', 'bcc' recipients")),
            ],
            options={
                'verbose_name_plural': 'Email Settings',
            },
        ),
    ]
