# Generated by Django 5.2.6 on 2025-09-16 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='from_address',
            field=models.EmailField(default='no-reply@rfms.local', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='from_name',
            field=models.CharField(default='RFMS Notifications', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='recipients',
            field=models.JSONField(default=dict),
        ),
    ]
