# Generated by Django 5.2.6 on 2025-09-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emailsettings_created_at_emailsettings_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsettings',
            name='recipients',
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='default_bcc',
            field=models.TextField(blank=True, help_text="Comma-separated list of default 'BCC' recipients."),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='default_cc',
            field=models.TextField(blank=True, help_text="Comma-separated list of default 'CC' recipients."),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='default_to',
            field=models.TextField(blank=True, help_text="Comma-separated list of default 'To' recipients."),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='encryption',
            field=models.CharField(choices=[('None', 'None'), ('STARTTLS', 'STARTTLS'), ('SSL/TLS', 'SSL/TLS')], default='STARTTLS', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='from_address',
            field=models.EmailField(default='no-reply@rfms.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='from_name',
            field=models.CharField(default='RFMS Notifications', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='host',
            field=models.CharField(max_length=255),
        ),
    ]
