# Generated by Django 5.2.6 on 2025-09-16 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_emailsettings_recipients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text="A unique key for the group, e.g., 'alerts', 'reports'.", max_length=50, unique=True)),
                ('name', models.CharField(help_text="A user-friendly name for the group, e.g., 'Alert Group'.", max_length=100)),
                ('chat_id', models.CharField(blank=True, help_text='The unique Chat ID for the Telegram group.', max_length=100)),
                ('link', models.URLField(blank=True, help_text='An optional invitation link or note for the group.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='default_bcc',
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='default_cc',
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='default_to',
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='bcc_recipients',
            field=models.TextField(blank=True, help_text='Comma-separated list of BCC email addresses.'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='cc_recipients',
            field=models.TextField(blank=True, help_text='Comma-separated list of CC email addresses.'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='to_recipients',
            field=models.TextField(blank=True, help_text='Comma-separated list of TO email addresses.'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='encryption',
            field=models.CharField(choices=[('STARTTLS', 'STARTTLS'), ('SSL/TLS', 'SSL/TLS'), ('None', 'None')], default='STARTTLS', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='from_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='from_name',
            field=models.CharField(default='RFMS Notifications', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='host',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
