# Generated by Django 5.2.6 on 2025-09-09 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_subsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Measuring Equipment name', max_length=100)),
                ('model_type', models.CharField(blank=True, help_text='Model / Type', max_length=100)),
                ('asset_id', models.CharField(blank=True, help_text='Asset / Serial ID', max_length=100)),
                ('location_in_depot', models.CharField(blank=True, help_text='Location within the Depot', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='infrastructure.depot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
