# Generated by Django 5.2.6 on 2025-09-10 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(help_text='Equipment Name', max_length=100)),
                ('make_modal', models.CharField(blank=True, help_text='Make/Modal', max_length=100)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('location_in_station', models.CharField(blank=True, help_text='Location within the station', max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='infrastructure.station')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
