# Generated by Django 5.2.6 on 2025-09-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_stationequipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationequipment',
            name='location_in_station',
            field=models.CharField(blank=True, help_text='Location within the Station', max_length=150),
        ),
    ]
