# Generated by Django 5.2.6 on 2025-09-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_alter_stationequipment_location_in_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
