# Generated by Django 5.2.6 on 2025-09-10 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_station_category_alter_station_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationequipment',
            name='installed_at',
        ),
        migrations.RemoveField(
            model_name='stationequipment',
            name='notes',
        ),
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stationequipment',
            name='address',
            field=models.CharField(blank=True, help_text='e.g., IP Address', max_length=150),
        ),
        migrations.AlterField(
            model_name='stationequipment',
            name='location_in_station',
            field=models.CharField(blank=True, help_text='Physical location in the station', max_length=150),
        ),
        migrations.AlterField(
            model_name='stationequipment',
            name='make_modal',
            field=models.CharField(blank=True, help_text='Make / Model', max_length=100),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='infrastructure.subsection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
