# Path: backend/failures/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views  # Use a direct module import

router = DefaultRouter()

# Registering the ViewSets correctly makes their @actions available
router.register(r'logs', views.FailureViewSet, basename='failure')
router.register(r'attachments', views.FailureAttachmentViewSet, basename='failure-attachment')
router.register(r'archived', views.ArchivedFailureViewSet, basename='archived-failure')

urlpatterns = [
    # Custom non-router views
    path('send-attachment-to-telegram/', views.SendAttachmentToTelegramView.as_view(), name='send-attachment-to-telegram'),
    
    # Include all URLs generated by the router (e.g., /logs/export_excel/)
    path('', include(router.urls)),
]
