# Generated by Django 5.2.6 on 2025-09-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('operator', 'Operator'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], default='viewer', max_length=20),
        ),
    ]
