# Generated by Django 5.2.6 on 2025-09-16 12:00

from django.db import migrations

def create_default_admin(apps, schema_editor):
    """
    Creates a default superuser 'admin' with password 'admin'.
    """
    User = apps.get_model('users', 'User')
    db_alias = schema_editor.connection.alias
    
    if not User.objects.using(db_alias).filter(username='admin').exists():
        admin_user = User.objects.using(db_alias).create_superuser(
            username='admin',
            password='admin',
            email='admin@rfms.local'
        )
        # Set the custom fields for the default admin
        admin_user.role = 'admin'
        admin_user.first_name = 'Default'
        admin_user.last_name = 'Admin'
        admin_user.save(using=db_alias)


def remove_default_admin(apps, schema_editor):
    """
    Removes the default superuser 'admin'.
    """
    User = apps.get_model('users', 'User')
    db_alias = schema_editor.connection.alias
    User.objects.using(db_alias).filter(username='admin', is_superuser=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_designation_user_role'),
    ]

    operations = [
        migrations.RunPython(create_default_admin, remove_default_admin),
    ]
