# Generated by Django 5.2.6 on 2025-09-16 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailureIDSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(default='RF', max_length=10)),
                ('padding', models.PositiveIntegerField(default=4)),
                ('reset_cycle', models.CharField(choices=[('never', 'Never'), ('yearly', 'Yearly'), ('monthly', 'Monthly')], default='yearly', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Failure ID Settings',
            },
        ),
    ]
