# Generated by Django 5.2.6 on 2025-09-18 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failureidsettings',
            name='padding',
        ),
        migrations.AddField(
            model_name='failureidsettings',
            name='last_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='failureidsettings',
            name='last_reset_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='failureidsettings',
            name='padding_digits',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='failureidsettings',
            name='reset_cycle',
            field=models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('never', 'Never')], default='yearly', max_length=10),
        ),
    ]
