# Generated by Django 5.2.6 on 2025-09-08 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0002_subsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fail_id', models.CharField(help_text='Unique Failure ID, can be auto-generated.', max_length=50, unique=True)),
                ('entry_type', models.CharField(choices=[('item', 'Item'), ('message', 'Message'), ('warning', 'Warning'), ('major', 'Major'), ('critical', 'Critical')], default='item', max_length=10)),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical')], default='Minor', max_length=10)),
                ('current_status', models.CharField(choices=[('Active', 'Active'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('On Hold', 'On Hold')], default='Active', max_length=20)),
                ('reported_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('remark_fail', models.TextField(blank=True, help_text='Initial notes about the failure.')),
                ('remark_right', models.TextField(blank=True, help_text='Notes on how the failure was resolved.')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failures', to='infrastructure.supervisor')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='failures', to='infrastructure.circuit')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failures', to='infrastructure.section')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failures', to='infrastructure.station')),
                ('sub_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failures', to='infrastructure.subsection')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
