# Generated by Django 5.2.5 on 2025-10-17 10:20

import django.utils.timezone
import failures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fail_id', models.CharField(blank=True, help_text='Unique Failure ID, auto-generated.', max_length=50, unique=True)),
                ('entry_type', models.CharField(choices=[('item', 'Item'), ('message', 'Message'), ('warning', 'Warning'), ('major', 'Major'), ('critical', 'Critical')], default='item', max_length=10)),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical')], default='Minor', max_length=10)),
                ('current_status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('On Hold', 'On Hold'), ('Information', 'Information')], default='Active', max_length=20)),
                ('reported_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('remark_fail', models.TextField(blank=True, help_text='Initial notes about the failure.')),
                ('remark_right', models.TextField(blank=True, help_text='Notes on how the failure was resolved.')),
                ('was_notified', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_reason', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FailureAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=failures.models.attachment_upload_path)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
