# Generated by Django 5.2.6 on 2025-09-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='fail_id',
            field=models.CharField(blank=True, help_text='Unique Failure ID, can be auto-generated.', max_length=50, unique=True),
        ),
    ]
