# Generated by Django 5.2.6 on 2025-09-16 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0002_alter_failure_fail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
