# Generated by Django 5.2.6 on 2025-09-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0003_alter_failure_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='fail_id',
            field=models.CharField(blank=True, help_text='Unique Failure ID, auto-generated.', max_length=50, unique=True),
        ),
    ]
